### PR TITLE
Refactor wallpaper into seperate crate

### LINKED ISSUE #15: Split setting the wallpaper into separate crate
As I mentioned in https://github.com/vineetred/flowy/issues/6#issuecomment-655078842, it would be ideal if the functionality for setting the wallpaper was moved to a new crate.

A similar crate, [`wallpaper`](https://github.com/reujab/wallpaper.rs), already exists, but it appears unmaintained and has more dependencies than necessary; therefore, a new crate could prove useful for other people. For `flowy`, the main benefits are improved compile times and a more modular code base.

I don't know how the crate should be called.

If someone other than me wants to implement this, you might find the [chapter about workspaces](https://doc.rust-lang.org/cargo/reference/workspaces.html) in the Cargo book useful.

### PR DESCRIPTION
**Pull request by mloehnig**
This moves logic to get and set a wallpaper into a separate crate.

This will provide future programmers a well maintained library/interface for getting and setting their wallpaper.

This PR is to address issue #15 .

### CODE REVIEW

**Comment by vineetred** [comment]
Have you tested this?

**Comment by mloehnig** [comment]
@vineetred I have tested it but only on a Ubuntu machine.

**Review by vineetred — CHANGES_REQUESTED** [review]
I want the new ```wallpapers``` crate to be at the same level as ```flowy```. The idea is that it will end up look like https://github.com/serde-rs/serde this -- all of the crates are at the same level. You will need to use workspaces for this. Check this out https://doc.rust-lang.org/book/ch14-03-cargo-workspaces.html.

Since most of the work already is done, you'll just need to put all the flowy stuff in one folder and name it flowy such that it is on the same directory level as ```wallpapers```. The dir will look something like this https://i.imgur.com/2NdW9GW.png.

**Comment by vineetred** [comment]
@swagggpickle you will need to use workspaces for this. Check this out https://doc.rust-lang.org/book/ch14-03-cargo-workspaces.html. Also, the dir will look something like this https://i.imgur.com/2NdW9GW.png.

**Comment by vineetred** [comment]
@swagggpickle I had pushed some commits to the repo before you made these changes. However, it creates conflicts. Can you just pull master from my repo so that there are no conflicts?

**Comment by mloehnig** [comment]
@vineetred I updated the project to have the correct layout that you desired. Sorry I miss understood what you wanted. Also I resolved the merge conflict.

**Comment by vineetred** [comment]
@swagggpickle no problem! Great work. Looks all set.

**Pull request merged**
