### PR TITLE
Windows support

### LINKED ISSUE #21: Windows support
**Is your feature request related to a problem? Please describe.**
Windows support needs to be added.

**Describe the solution you'd like**
The only way I can think of is by using the winapi

**Describe alternatives you've considered**
Using image viewer tools. But that solution is too bulky so scrapped it.

**Additional context**
The Rust crate ```wallpaper``` already does this. Since it is unmaintained, it's methods can be ported instead to flowy.

### PR DESCRIPTION
**Pull request by Aloso**
This adds support for windows. I also uncommented the windows part in the GitHub workflow.

**WARNING**: I haven't tested this, please make sure that it works before merging.

The code is taken from the [wallpaper crate](https://docs.rs/wallpaper/2.0.1/wallpaper/) and slightly modified.

### CODE REVIEW

**Comment by vineetred** [comment]
The last two commits of this PR fail the CI pipeline. The code doesn't compile.

**Comment by vineetred** [comment]
@Aloso one of the reasons I have not ported the Windows bit from the ```wallpaper``` crate is because I have no system to check if it works. I'll see how I can share this binary -- meanwhile, see if you can do the same as well.

**Comment by mloehnig** [comment]
@vineetred I tested this branch on my Windows machine and I did not have any problem.

**Comment by vineetred** [comment]
> @vineetred I tested this branch on my Windows machine and I did not have any problem.

Amazing. Merging right away then! Windows support is great news!

**Comment by Aloso** [comment]
This is great! I guess the documentation still needs to be updated before the next release.

**Comment by vineetred** [comment]
> documentation still needs to be updated before the next release.

@Aloso yep! Need to revamp it as it's going to be a major release. Posted on the issue tracker already.

**Pull request merged**
